baseURL = "https://ffkkinos.com"
languageCode = "en-us"
title = "ffkkinos"
theme = "nanika"
tableOfContents = true
enableGitInfo = true
renderParameters.FootnoteReturnLinkContents = "<-"
FootnoteReturnLinkContents = "â†‘"